### ISSUE TITLE
Procuro Grupo para turma da Noite!

### ISSUE THREAD

**Issue by preira** [isel-leic-pi/PI-1819i-LI51N#1]
Caros colegas, como não conheço ninguém, venho socorrer-me deste meio para procurar um grupo no qual me possa integrar.

**Comment by iSW007** [comment]
> Caros colegas, como não conheço ninguém, venho socorrer-me deste meio para procurar um grupo no qual me possa integrar.

Vem para o meu grupo #2

**Comment by ambccp** [comment]
Caros colegas, também estou à procura de grupo

**Comment by preira** [comment]
> Caros colegas, também estou à procura de grupo

Não sei se o colega @iSW007 concorda, mas o grupo 2 ainda não está completo.

**Comment by iSW007** [comment]
Estejam à vontade!

**Comment by ambccp** [comment]
Então para o grupo 2 também

**Comment by ambccp** [comment]
Já ficou completo
